- name: install and run nginx
  hosts: web
  become: yes
  tasks:
   - name: install nginx package
     ansible.builtin.package:
      name: nginx
      state: present
   - name: Enable service nginx
     ansible.builtin.service:
       name: nginx
       enabled: yes
   - name: run the nginx
     ansible.builtin.service:
      name: nginx
      state: started
- name: Remove file (delete file)
  ansible.builtin.file:
    path: /usr/share/nginx/html/*
    state: absent

- name: Download file from a file path
  ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp/web.zip
- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: unzip /tmp/web.zip
    dest: /usr/share/nginx/html


    
